version: "3.8"

services:
  app:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
