version: "3.8"

services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules/  # Prevents overriding node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    restart: unless-stopped

  frontend:
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules/
    working_dir: /app
    command: [ "sh", "-c", "npm install && npm run dev" ]
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures hot reload works
    depends_on:
      - backend
    restart: unless-stopped

