#backend docker file
# Use Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --omit=dev  # Install production dependencies

# Copy source code
COPY . .

# Expose backend port
EXPOSE 3000

# Start backend
CMD ["npm", "run", "dev"]
